<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpqlVez\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpqlVez/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXpqlVez.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXpqlVez\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXpqlVez\App_KernelProdContainer([
    'container.build_hash' => 'XpqlVez',
    'container.build_id' => '385b78ac',
    'container.build_time' => 1632820402,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpqlVez');
