<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNFr0dJp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNFr0dJp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNFr0dJp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNFr0dJp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNFr0dJp\App_KernelDevDebugContainer([
    'container.build_hash' => 'NFr0dJp',
    'container.build_id' => '790c7464',
    'container.build_time' => 1637595224,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNFr0dJp');
