<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPrMOQiQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPrMOQiQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPrMOQiQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPrMOQiQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPrMOQiQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PrMOQiQ',
    'container.build_id' => 'a62d1408',
    'container.build_time' => 1636968375,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPrMOQiQ');
