<?php

namespace ContainerXpqlVez;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UKTcX8_Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored.UKTcX8.' shared service.
     *
     * @return \App\Security\LoginFormAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $AbstractLoginFormAuthenticator argument is type-hinted with the non-existent class or interface: "App\\Security\\LoginFormAuthenticator".');
    }
}
