<?php

namespace ContainerXpqlVez;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UPM6NlVService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.UPM6NlV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UPM6NlV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'UserRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'UserRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
